Development
zenott/Embedding-Images-and-Video pull request #1
Opened 2019-02-25 23:09 UTC by zenott

2019-02-25 23:53 UTC, zlayabekrija requested changes
This was excellent first try guys (especially the song). There are things to be changed.
Refrain yourself from doing inline styling, use css, also I see a lot of repetition of code (image width), make classes instead. 
Please before submitting your code, run https://validator.w3.org/ to validate your html and css. Also, use https://htmlpreview.github.io/ to preview your page on the live server. There can be a lot of differences between local and live preview.

After you are done with these changes, please submit another review request.

2019-02-25 23:53 UTC, zlayabekrija commented on style.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif';
sans-serif should be within ''

2019-02-25 23:53 UTC, zlayabekrija commented on index.html
> +      <iframe
iframe should use digits not %

2019-02-25 23:53 UTC, zlayabekrija commented on index.html
> +      <div class="other-videos">
Other videos should be on the right side of the main video, please move them accordingly.
Comments should be underneath the video.

2019-02-25 23:53 UTC, zlayabekrija commented on index.html
> +      (function(d, e, s) {
js should go to script.js file or similar.

2019-02-25 23:53 UTC, zlayabekrija commented on index.html
> +    <nav class="navbar">
Please redo the navbar so it looks more youtube-like. Use fontawsome for icons if you like, and add the search field.

2019-02-26 23:06 UTC, AlejoCode commented
All improves taked into account, please review all the new changes.

Thank you so much @zlayabekrija zlayabekrija

2019-02-27 18:06 UTC, zlayabekrija requested changes
Please adjust required changes .

2019-02-27 18:06 UTC, zlayabekrija commented on style.css
> +    padding-top: 56.25%;
too big padding please adjust it.

2019-02-27 18:06 UTC, zlayabekrija commented on style.css
> +    position: absolute;
unnecessary remove it please

2019-02-27 18:06 UTC, zlayabekrija commented on style.css
> +    top: 0;
unnecessary

2019-02-27 18:06 UTC, zlayabekrija commented on style.css
> +    width: 100%;
unnecessary

2019-02-27 18:06 UTC, zlayabekrija commented on style.css
> +    height: 100%;
unnecessary

2019-02-27 21:16 UTC, zenott commented
We did the requested changes. We had to use 100% for the video container to give it responsiveness.
Please let us know if it is good or should we use another solution.
Thank you.

2019-02-28 18:43 UTC, zlayabekrija approved these changes
Thumbs up from me 👍

2019-02-28 20:49 UTC, merged